apiVersion: v1
kind: Service
metadata:
  name: service-greeting-jonathan-service 
spec:
  ports:
  - port: 30000
    nodePort: 30000
    targetPort: 8080 
  selector:
    app: service-greeting-jonathan
  type: NodePort
