apiVersion: v1
kind: Service
metadata:
  name: service-greeting-gary-service 
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: 8080 
  selector:
    app: service-greeting-gary
  type: NodePort
