name: Github Action sharing - PR test  

on:
  pull_request:
    branches:
      - master

jobs:
  PR-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup golang 
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Initial mod
        run: make mod
      - name: Test
        run: make test
      - name: Coverage
        run: make coverage
